#!/bin/sh

set -e

echo ""
echo "  Vim Configuration"
echo ""

echo "  + Setting up packages..."
rm -rf pack/

mkdir -p pack/general/start
pushd pack/general/start > /dev/null

git clone -q https://github.com/mileszs/ack.vim.git
git clone -q https://github.com/ctrlpvim/ctrlp.vim.git
git clone -q https://github.com/mattn/emmet-vim.git
git clone -q https://github.com/pangloss/vim-javascript.git
git clone -q https://github.com/tpope/vim-bundler.git
git clone -q https://github.com/tpope/vim-commentary.git
git clone -q https://github.com/tpope/vim-cucumber.git
git clone -q https://github.com/tpope/vim-dispatch.git
git clone -q https://github.com/tpope/vim-endwise.git
git clone -q https://github.com/tpope/vim-fugitive.git
git clone -q https://github.com/tpope/vim-markdown.git
git clone -q https://github.com/tpope/vim-rails.git
git clone -q https://github.com/tpope/vim-rbenv.git
git clone -q https://github.com/tpope/vim-surround.git

popd > /dev/null

echo "  + Setting up symlinks..."
ln -fs vimrc ~/.vimrc

echo ""
echo "  We're ready to rock!"
