#!/bin/sh

set -e

echo ""
echo "  Ealden's Vim Config"
echo ""

if [ ! -n "$GOPATH" ]; then
  echo '  x Please set $GOPATH for vim-go plugin'
  exit
fi

# Initialize submodules
echo "  + Initializing submodules..."
git submodule init
git submodule update

# Install bundles
echo "  + Installing bundles..."
vim +PluginUpdate +qall

# Set up symlinks
echo "  + Setting up symlinks..."
rake

echo ""
echo "  We're ready to rock!"
