#!/bin/sh

set -e

echo ""
echo "  Vim Configuration"
echo ""

echo "  + Setting up symlinks..."
rm -f ~/.vim
rm -f ~/.vimrc

ln -fs `pwd`/ ~/.vim
ln -fs `pwd`/vimrc ~/.vimrc

echo "  + Setting up packages..."
rm -rf pack/

mkdir -p pack/all/start
cd pack/all/start

git clone -q https://github.com/Chiel92/vim-autoformat.git
git clone -q https://github.com/ctrlpvim/ctrlp.vim.git
git clone -q https://github.com/mattn/emmet-vim.git
git clone -q https://github.com/mileszs/ack.vim.git
git clone -q https://github.com/pangloss/vim-javascript.git
git clone -q https://github.com/posva/vim-vue.git
git clone -q https://github.com/tpope/vim-bundler.git
git clone -q https://github.com/tpope/vim-commentary.git
git clone -q https://github.com/tpope/vim-cucumber.git
git clone -q https://github.com/tpope/vim-endwise.git
git clone -q https://github.com/tpope/vim-fugitive.git
git clone -q https://github.com/tpope/vim-markdown.git
git clone -q https://github.com/tpope/vim-rails.git
git clone -q https://github.com/tpope/vim-rbenv.git
git clone -q https://github.com/tpope/vim-repeat.git
git clone -q https://github.com/tpope/vim-surround.git

cd ../../../

echo "  + Installing formatters..."
npm install -g js-beautify
gem install rubocop
pip install yapf

echo ""
echo "  We're ready to rock!"
